//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAssociate
    {
        public long ClientAssociateId { get; set; }
        public long ClientId { get; set; }
        public long IndividualId { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime DateInvited { get; set; }
        public Nullable<System.DateTime> DateAccepted { get; set; }
        public Nullable<long> ClientAssociateRootFolderId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Individual Individual { get; set; }
    }
}
