//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolderPermission
    {
        public long FolderPermissionId { get; set; }
        public Nullable<long> FolderId { get; set; }
        public Nullable<long> OwnerId { get; set; }
        public Nullable<long> IndividualId { get; set; }
        public int RoleId { get; set; }
        public Nullable<bool> CanCreate { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public Nullable<bool> CanUpload { get; set; }
        public Nullable<bool> CanDownload { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Role_RoleId { get; set; }
        public Nullable<long> User_UserId { get; set; }
    
        public virtual Folder Folder { get; set; }
        public virtual Individual Individual { get; set; }
    }
}
